spring:
  application:
    name: "Blog-App"

  datasource:
    url: jdbc:mysql://localhost:3306/blogdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    user:
      name: user
      password: user
      roles:
        - GUEST